# auto: true

markdown: kramdown
highlighter: rouge
paginate: 8
permalink: /:title
encoding: UTF-8
gems: [jekyll-paginate]
safe: false
title: 人生和技术都如白驹过隙
url: http://jplee1969.github.io

author_info: <a href="http://jplee1969.github.io/">李俊平</a>

myblog:
  gavatar: images/1.jpg
  gpname: jplee
  github: https://github.com/jplee1969
  email: mailto:jplee@163.com
  coverimgs: []
  postbgimg: []

categories: [python, books, teaching, R ]
gems:[category_archive_plugin, monthly_archive_plugin ]
